### PR TITLE
model filter modal

### PR DESCRIPTION
**Pull request by nimaai**

### CODE REVIEW

**Review by urs-van-binsbergen — COMMENTED** [review]
- [x] First feedback from testing: I would remove the _"old" inline filter form_ altogether and replace it by the filter bubble everywhere, otherwise the flow is confusing. 
- [x] label html-for "delegation", but the field's id is "user-id". Some for "pool", "pool-id"
- [ ] `(t :!borrow.rental-show.user-or-delegation-personal-postfix)` - this is a cross reference to a translation key belonging to another feature, which I would avoid. We should move this expression to "GENERAL PHRASES".- (...review in progress)

UI/Design improvements (as discussed: probably in a separate pull request, partly by frontend dept.):
- [ ] Wrap form elements in a `form` tag, submittable by enter
- [x] Wording according to design specs
- [ ] Reset button: Not in design spec, but maybe useful; breaks button layout however.
- [ ] Improve Availability filters (from, to, quantity). Probably remove the expand/collapse logic. 
- [x] Quantity with `MinusPlusControl`
- [ ] Discuss placeholder attributes (not clear from design spec), in general. Here specifically for the keyword field. "Suchbegriff eingeben" is a call to action which is not ideal imo.

Questions
- [x] dependency ["react" :as React] - is this is for some side effect? or not needed?

**Comment by nimaai** [comment]
@eins78 please have a look. the unchecked tasks would eventually be dealt with in separate tickets. i would like to merge this as it is now. so if ok from your side, then i would start fixing the tests.

**Review by eins78 — COMMENTED** [review]
i agree with the open points from urs, and have some more. if there is a follow-up ticket they can also be solved there. 

- [x] https://github.com/leihs/leihs-borrow/issues/31
- [ ] missing translations and correct date formatting (see shopping cart feature)
- [x]  need to clear up the cancel/reset button and how to close the modal. for now 'cancel' button can be commented out. if we keep it we need to fix the layout
- [x] "stringify/humanize current filter" will come in a seperate ticket. please prepare the following: put the equivalent of `JSON.stringify(currentFilters)` in the label text of the button if `[:ls :debug :filter-labels]` is set true  in app-db

**Comment by nimaai** [comment]
@eins78 in regards to 4th point: why not `[:meta :app :debug]` ?

**Comment by eins78** [comment]
> @eins78 in regards to 4th point: why not `[:meta :app :debug :filter-labels]` ?

because it should be persisted in localstorage/across reloads – otherwise we would not need app-db at all and could just set `window.SOMETHING`.

**Pull request closed without merging**
